### ISSUE TITLE
[Question] Are trained files available?

### ISSUE THREAD

**Issue by y-ich** [Rochester-NRT/RocAlphaGo.data#1]
Hi.

I expanded *.zip files but I could not find' json' files that specify model architectures and `hdf5` files for the weights.
Aren't they available yet?

**Comment by wrongu** [comment]
We have some models in the early stages of training. I just uploaded one in case you'd like to experiment with it. Training is very slow at the moment as we haven't implemented distributed SGD.

**Comment by y-ich** [comment]
Thank you!
